<div class="my-car-tabs">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" href="#select-car-tab"><?php echo __('Select Car'); ?></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#my-selected-car-tab"><?php echo __('My Selected Car'); ?></a>
        </li>
    </ul>

    <div class="tab-content">
        <div id="select-car-tab" class="tab-pane fade">
            <?php echo $block->getChildHtml('razoyo_carprofile_customer_select_car'); ?>
        </div>
        <div id="my-selected-car-tab" class="tab-pane fade">
            <?php echo $block->getChildHtml('razoyo_carprofile_customer_my_selected_car'); ?>
        </div>
    </div>
</div>

<script type="text/javascript">
require([
    'jquery',
    'jquery/ui',
    'Magento_Ui/js/modal/modal'
], function($, jqueryUi, modal) {
    $(document).ready(function () {
        // Handle tab switching
        $('.my-car-tabs .nav-tabs a').on('click', function (e) {
            e.preventDefault();
            var tabId = $(this).attr('href');
            $('.my-car-tabs .tab-content .tab-pane').hide(); // Hide all tab content
            $(tabId).show(); // Show selected tab content
            
            // Update active state of tabs
            $('.my-car-tabs .nav-tabs a').removeClass('active');
            $(this).addClass('active');
        });

        // Show initial active tab content
        $('.my-car-tabs .nav-tabs a.active').trigger('click');
    });
});
</script>
